vile:
  ignore:
    - .build
    - coverage
    - node_modules
    - lib
    - tags
    - .test
    - .ctags
    - .git
    - circle.yml
    - .editorconfig
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .npmrc
    - README.md
    - .vile.yml
    - .vilerc

length:
  config:
    file: 120
    line: 80

coverage:
  config:
    path: coverage/lcov.info

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: []
    ignore_deps:
      - "@forthright/*"
      - coffee-script
      - istanbul
      - npm-check-updates
      - release-it

license:
  config:
    ignored:
      - tweetnacl
      - commander
      - growl
      - cli-table
      - debug
      - classifier
      - dox
      - event-stream
      - map-stream
      - microee
      - split
      - tv4
      - forthright/vile-comment
      - forthright/vile-eslint
      - forthright/vile-nsp
      - forthright/vile-whitespace
    allowed:
      - CC-BY-3.0
      - The MIT License
      - MIT
      - MIT AND CC-BY-3.0
      - MPL
      - MPL-2.0
      - MPLv2.0
      - Public Domain
      - PSF
      - BSD
      - BSD-3-Clause
      - BSD-2-Clause
      - BSD-3-Clause AND MIT
      - BSD-2-Clause OR MIT
      - BSD-2-Clause OR WTFPL
      - BSD-2-Clause OR MIT OR Apache-2.0
      - Unlicense
      - Artistic-2.0
      - ISC
      - WTFPL
      - Apache
      - Apache2
      - Apache-2.0
      - Apache 2.0
      - Apache*
      - Apache License, Version 2.0
      - Apachev2
      - WTFPL
      - GPL
